spring:
  datasource:
    url: jdbc:postgresql://localhost:11432/microservice-organization
    username: anton
    password: 1234
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
    validate-on-migrate: false
    baseline-on-migrate: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  authenticationServiceUrl:
    value: microservice-authentication:8080/api/v1/authenticate
server:
  port: 8082
logging:
  level:
    org:
      hibernate: Error
      springframework:
        web: DEBUG
        security: DEBUG
    root: INFO
