version: '3.1'

services:

  db-organization:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: anton
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: microservice-organization
    ports:
      - "11432:5432"

  db-order:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: anton
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: microservice-order
    ports:
      - "9432:5432"

  db-authentication:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: anton
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: microservice-authentication
    ports:
      - "8432:5432"

  microservice-authentication:
    container_name: microservice-authentication
    build:
      context: ..
      dockerfile: docker/builder/components/Dockerfile
      args:
        BUILD_PATH: microservice-authentication
    ports:
      - "8080:80"
    environment:
      - "spring.datasource.url=jdbc:postgresql://db-authentication:8432/microservice-organization"
      - "spring.datasource.username=anton"
      - "spring.datasource.password=1234"
      - "spring.flyway.enabled=true"
      - "spring.jpa.show-sql=true"
      - "spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
    depends_on:
      - "db-authentication"

  microservice-order:
    container_name: microservice-order
    build:
      context: ..
      dockerfile: docker/builder/components/Dockerfile
      args:
        BUILD_PATH: microservice-order
    ports:
      - "8081:80"
    environment:
      - "spring.datasource.url=jdbc:postgresql://db-organization:9432/microservice-organization"
      - "spring.datasource.username=anton"
      - "spring.datasource.password=1234"
      - "spring.flyway.enabled=true"
      - "spring.jpa.show-sql=true"
      - "spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
    depends_on:
      - "db-organization"
      - 'microservice-authentication'

  microservice-organization:
    container_name: microservice-organization
    build:
      context: ..
      dockerfile: docker/builder/components/Dockerfile
      args:
        BUILD_PATH: microservice-organization
    ports:
      - "8082:80"
    environment:
      - "spring.datasource.url=jdbc:postgresql://db-organization:11432/microservice-organization"
      - "spring.datasource.username=anton"
      - "spring.datasource.password=1234"
      - "spring.flyway.enabled=true"
      - "spring.jpa.show-sql=true"
      - "spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
    depends_on:
      - "db-organization"
      - 'microservice-authentication'