# Use postgres/example user/password credentials
version: '3.1'

services:

  db-order:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: anton
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: microservice-order
    ports:
      - 9432:5432
