spring:
  datasource:
    url: jdbc:postgresql://localhost:9432/microservice-order
    username: anton
    password: 1234
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
    validate-on-migrate: false
    baseline-on-migrate: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  authenticationServiceUrl:
    value: http://localhost:8080/api/v1/
server:
  port: 8081
logging:
  level:
    org:
      springframework:
        security: DEBUG
